#!/usr/bin/env bash
set -euo pipefail

ENV_FILE=".env"

echo "=== DeFi Trading Bot Setup ==="
echo ""

# Load existing .env if present
if [ -f "$ENV_FILE" ]; then
    echo "Found existing .env file."
    read -rp "Use existing values as defaults? [Y/n] " use_existing
    if [[ "${use_existing:-Y}" =~ ^[Yy]$ ]]; then
        set -a
        source "$ENV_FILE"
        set +a
    fi
    echo ""
fi

prompt() {
    local var_name="$1"
    local display_name="$2"
    local default="${!var_name:-}"
    local is_secret="${3:-false}"

    if [ -n "$default" ]; then
        if [ "$is_secret" = "true" ]; then
            local masked="${default:0:6}...${default: -4}"
            read -rp "$display_name [$masked]: " value
        else
            read -rp "$display_name [$default]: " value
        fi
        eval "$var_name=\"${value:-$default}\""
    else
        if [ "$is_secret" = "true" ]; then
            read -rsp "$display_name: " value
            echo ""
        else
            read -rp "$display_name: " value
        fi
        if [ -z "$value" ]; then
            echo "  (skipped)"
        fi
        eval "$var_name=\"$value\""
    fi
}

echo "-- Chain RPC Endpoints --"
echo "(Leave blank to skip a chain)"
echo ""

prompt ARBITRUM_RPC_HTTP "Arbitrum HTTP RPC"
prompt ARBITRUM_RPC_WS   "Arbitrum WebSocket RPC"
echo ""
prompt BASE_RPC_HTTP     "Base HTTP RPC"
prompt BASE_RPC_WS       "Base WebSocket RPC"
echo ""
prompt POLYGON_RPC_HTTP  "Polygon HTTP RPC"
prompt POLYGON_RPC_WS    "Polygon WebSocket RPC"
echo ""

echo "-- Wallet --"
prompt PRIVATE_KEY "Private key (hex)" true
echo ""

echo "-- Execution Mode --"
echo "  simulate = log opportunities only (no real txs)"
echo "  execute  = send real transactions"
read -rp "Mode [${EXECUTION_MODE:-simulate}]: " mode_input
EXECUTION_MODE="${mode_input:-${EXECUTION_MODE:-simulate}}"
echo ""

# Write .env
cat > "$ENV_FILE" <<EOF
# Generated by start.sh — $(date -Iseconds)
ARBITRUM_RPC_HTTP=${ARBITRUM_RPC_HTTP:-}
ARBITRUM_RPC_WS=${ARBITRUM_RPC_WS:-}
BASE_RPC_HTTP=${BASE_RPC_HTTP:-}
BASE_RPC_WS=${BASE_RPC_WS:-}
POLYGON_RPC_HTTP=${POLYGON_RPC_HTTP:-}
POLYGON_RPC_WS=${POLYGON_RPC_WS:-}
PRIVATE_KEY=${PRIVATE_KEY:-}
EXECUTION_MODE=${EXECUTION_MODE}
EOF

chmod 600 "$ENV_FILE"
echo ".env written (permissions 600)."
echo ""

# Export for the build & run
set -a
source "$ENV_FILE"
set +a

# Patch execution mode into config.yaml at runtime via sed
CONFIG_TMP=$(mktemp)
sed "s/^  mode: .*/  mode: ${EXECUTION_MODE}/" config.yaml > "$CONFIG_TMP"

echo "Building..."
make build
echo ""

echo "Starting trader (mode=${EXECUTION_MODE})..."
exec ./bin/trader -config "$CONFIG_TMP"
